-- PREVIEW (READ-ONLY) — Mutirão Fremix AGO_26
-- Objetivo: validar volume e classificação antes do INSERT.

with origem(nome, funcao, idade, indicacao, status_candidatura, observacoes, motivo_reprovacao, resultado_teste) as (
  values
  ('ARNALDO FERREIRA', 'ENCARREGADO DE OBRAS', null, null, 'aprovado', 'Trabalha como operador em GRU', null, null),
  ('JOSÉ VALDIR', 'RASTELEIRO', null, 'Ricardo Barbieri', 'aprovado', 'já trabalhou na Fremix', null, null),
  ('FABIO ALMEIDA', 'MESISTA', null, 'Ricardo Barbieri', 'aprovado', 'já trabalhou na Fremix', null, null),
  ('FERNANDO SILVA GOMES', 'APONTADOR DE OBRAS', 40, null, 'reprovado', 'já trabalhou na Fremix', 'já trabalhou na Fremix', null),
  ('EDSON SERRANO', 'MOTORISTA BASCULANTE', 54, null, 'aprovado', 'ja trabalhou com diversos caminhões | Flag planilha: Fazer teste', null, null),
  ('RITERIS JOSÉ SILVA SOUZA', 'MOTORISTA DE CAMINHÃO', 46, null, 'aprovado', 'Onibus, Moop, Coletivo, faculdade de Logistica trancada | Flag planilha: Fazer teste', null, null),
  ('ADEILDO XAVIER DA SILVA', 'OPERADOR DE VIBRO', 51, 'Luciano op de Rolo', 'reprovado', 'saiu da Schunk porque não fazia horas extras', 'saiu da Schunk porque não fazia horas extras', null),
  ('FERNANDO JOSÉ SILVA', 'OP DE PA CARREGADEIRA', 39, null, 'aprovado', null, null, null),
  ('OTÁVIO OLIVEIRA SILVA', 'MANGUEIRISTA', 38, null, 'aprovado', 'Já trabalhou na Fremix (Aelson)', null, null),
  ('IGO DUARTE DE SOUSA', 'MOTORISTA DE CAMINHÃO', 37, 'Willy (irmão)', 'reprovado', null, null, null),
  ('LEIS PEREIRA', 'AJUDANTE', 41, 'Willian', 'reprovado', null, null, null),
  ('MAURICIO PEREIRA DA SILVA', 'MOTORISTA DE CAMINHÃO', 52, null, 'reprovado', 'já trabalhou na Fremix', 'já trabalhou na Fremix', null),
  ('JOSELITO JOSE DE SOUSA', 'RASTELEIRO', 58, null, 'aprovado', 'Muito experiente', null, null),
  ('FABIO PEREIRA BRITO', 'MOTORISTA DE CAMINHÃO', 39, 'Gustavo', 'reprovado', 'já trabalhou na Fremix', 'já trabalhou na Fremix', null),
  ('MARCOS DE FREITAS', 'AJUDANTE', 48, null, 'aprovado', null, null, null),
  ('JEFFERSSON SALES TEIXEIRA', 'AJUDANTE', 39, null, 'reprovado', 'Já trabalhou na Usivix', 'Já trabalhou na Usivix', null),
  ('KHEVYN BRYAN GARCIA', 'AJUDANTE', 18, 'Jailson (Padrastro)', 'reprovado', null, null, null),
  ('CHARLI BARBOSA AZEVEDO', 'OPERADOR DE MAQUINAS', 36, null, 'aprovado', 'Trabalhou em GRU - Opera diversas maquinas', null, null),
  ('FELIPE CARVALHO CAMILO', 'AJUDANTE', null, 'Plinio (Técnico)', 'reprovado', null, null, null),
  ('DAVI CARLOS SILVA MENDES', 'AJUDANTE', 28, 'Plinio (Técnico)', 'reprovado', null, null, null),
  ('HAZIELL ALVES NOGUEIRA', 'AJUDANTE', 27, 'Eurismar', 'aprovado', null, null, null),
  ('JORGE SANTOS DE OLIVEIRA', 'OPERADOR DE MAQUINAS', 47, null, 'reprovado', 'CNH AB provisória', 'CNH AB provisória', null),
  ('CICERO RICARDO SOUZA', 'OP DE BOBCAT', null, null, 'triagem', null, null, null),
  ('ALVARO MOREIRA DOS SANTOS', 'AJUDANTE', 38, null, 'aprovado', 'já foi apontador / Rasteleiro', null, null),
  ('VICTOR AUGUSTO DO NASCIMENTO', 'RASTELEIRO', 37, null, 'aprovado', null, null, null),
  ('GUTEMBERGUE PEREIRA FELIX', 'OP DE BOBCAT', 34, 'Gilberto (op de bobcat)', 'aprovado', 'Também é Motorista | Flag planilha: Fazer teste', null, null),
  ('JOSINALDO FERREIRA BARROS', 'MOTORISTA BASCULANTE', 48, null, 'aprovado', 'Flag planilha: Fazer teste', null, null),
  ('FELIPE PEREIRA NEPONUCEMO', 'APONTADOR DE OBRAS', 21, 'Alan (Técnico de Segurança)', 'reprovado', null, null, null),
  ('MATHEUS VINICIUS CAMPO', 'AJUDANTE', 24, null, 'aprovado', 'já trabalhou na Fremix / tem experiancia de apontador na FBS)', null, null),
  ('JOVANILSON PEREIRA GOMES', 'RASTELEIRO', 35, 'Thiago Silva', 'aprovado', 'já trabalhou na Fremix', null, null),
  ('ILDEU APARECIDO DOS REIS', 'RASTELEIRO', 60, null, 'aprovado', 'já trabalhou na Fremix', null, null),
  ('WALTER RODRIGUES DE AGUIAR', 'MOTORISTA BASCULANTE', 53, null, 'aprovado', null, null, null),
  ('RONALDO BARBOSA DE LUCENA', 'OPERADOR DE VIBRO', 49, null, 'aprovado', 'já trabalhou na Fremix / atualmente na FBS', null, null),
  ('MARCELO ARAUJO DE SOUZA', 'OP DE ROLO', 45, null, 'aprovado', 'Flag planilha: Fazer teste', null, null),
  ('MARCOS ANTONIO DA SOUZA', 'MESISTA', 25, 'Francisco Patricio', 'aprovado', null, null, null),
  ('CICERO DANRLEY CARVALHO SOUZA', 'AJUDANTE', 29, 'Jose Cicero', 'aprovado', null, null, null),
  ('JANDERSON RYAN SILVA DOS SANTOS', 'AJUDANTE', 24, 'Geandson', 'reprovado', 'já trabalhou na Fremix / Thiago Silva', 'já trabalhou na Fremix / Thiago Silva', null),
  ('JAMES DE ALMEIDA BARBOSA', 'MOTORISTA CARRETEIRO', 43, 'Ricardo Nobre', 'aprovado', 'experiente em caçamba | Flag planilha: Fazer teste', null, null),
  ('MARCOS TADEU DE OLIVEIRA', 'AJUDANTE', 37, 'Gustavo', 'aprovado', null, null, null),
  ('MANUEL MARCOLINO MACHADO', 'RASTELEIRO', 39, 'Max Alan', 'aprovado', null, null, null),
  ('JOSE ARNALDO GUILHERME', 'RASTELEIRO', 53, 'Davi Carlos', 'aprovado', null, null, null),
  ('MANOEL SILVA SANTOS', 'OPERADOR DE VIBRO', 34, null, 'aprovado', 'Flag planilha: Fazer teste', null, null),
  ('UOZITON MANOEL GOMES', 'OPERADOR DE VIBRO', 38, null, 'aprovado', 'já trabalhou como encarregado, opera todas as maquinas de pavimentação menos fresa | Flag planilha: Fazer teste', null, null),
  ('DANILO THOMAZ D URBANO', 'OP DE BOBCAT', 36, 'Aila', 'aprovado', null, null, null),
  ('ALEXSANDRO DOS SANTOS RODRIGUES', 'AJUDANTE', 34, 'Jailson', 'aprovado', 'Soldador', null, null),
  ('RENILDO OLIVEIRA MOREIRA', 'AJUDANTE', 29, null, 'triagem', 'já trabalhou na Fremix', null, null),
  ('JOSÉ DA SILVA LIMA', 'MOTORISTA BASCULANTE', 62, null, 'teste', 'Flag planilha: Fazer teste', null, 'PENDENTE'),
  ('MARIVALDO EVANGELISTA DE SOUZA', 'AJUDANTE', 35, 'Jose Cicero', 'aprovado', null, null, null),
  ('DENIS DE PAULA MACHADO', 'AJUDANTE', 34, 'Jose Cicero', 'aprovado', null, null, null),
  ('EDINALDO DE OLIVEIRA', 'MOTORISTA DE CAMINHÃO', 43, null, 'aprovado', 'Flag planilha: Fazer teste', null, null),
  ('HERICLES ARAUJO DE SOUZA', 'AJUDANTE', 31, 'Fabio', 'aprovado', null, null, null),
  ('ROGERIO DAS NEVES COSTA', 'MOTORISTA ONIBUS', 46, 'André Luiz', 'aprovado', 'Flag planilha: Fazer teste', null, null),
  ('JOÃO RICARDO DA SILVA', 'MOTORISTA CARRETEIRO', 56, null, 'reprovado', null, null, null),
  ('KELVIN DA SILVA BARBOSA', 'AJUDANTE', 26, 'Rafael Pinheiro', 'reprovado', null, null, null),
  ('KAIQUE SOUSA', 'OPERADOR DE VIBRO', 33, 'Rafael Pinheiro', 'aprovado', 'Flag planilha: Fazer teste', null, null),
  ('ARTUR SUDARIO DE ASSIS', 'AJUDANTE', 29, 'Plinio (Técnico)', 'aprovado', 'Esposa Gravida', null, null),
  ('JOÃO ROMANATO', 'MOTORISTA DE CAMINHÃO', 52, 'Wilson', 'aprovado', null, null, null),
  ('SAMUEL SANTOS AZEVEDO', 'MOTORISTA DE CAMINHÃO', 40, 'José Hilton', 'aprovado', null, null, null),
  ('LUIZ ANTONIO DOS SANTOS SILVA', 'MOTORISTA BASCULANTE', 53, 'Alexandre - Contabilidade', 'aprovado', null, null, null),
  ('CARLOS EDUARDO DA SILVA', 'RASTELEIRO', 43, null, 'aprovado', null, null, null),
  ('ROMILDO ALVES PEREIRA', 'MOTORISTA DE CAMINHÃO', 71, null, 'aprovado', null, null, null),
  ('FELIPE FRANCISCO ALVES', 'AJUDANTE', 27, 'Cleder / Plinio', 'reprovado', null, null, null),
  ('DIEGO JONE RODRIGUES', 'AJUDANTE', 33, null, 'aprovado', null, null, null),
  ('WHASHINGTON DO CARMO MELO', 'AJUDANTE', 40, 'Eurismar', 'aprovado', null, null, null),
  ('BRUNO EDUARDO F DE MATOS', 'MOTORISTA DE CAMINHÃO', 31, null, 'aprovado', 'Trabalhou na Fremix - Comboio', null, null),
  ('ROGÉRIO FERREIRA SANTANA', 'AJUDANTE', 23, 'Rodrigo / Geisson', 'aprovado', null, null, null),
  ('JOÃO PAULO CASSIANO', 'APONTADOR DE OBRAS', 38, 'Gabriel Evaristo', 'aprovado', 'Apontador de Infra, Formado em Tec. Edificações', null, null),
  ('CARLOS HENRIQUE MONTEIRO', 'TEC DE SEGURANÇA', 54, null, 'reprovado', null, null, null),
  ('WILLIN GABRIEL NASCIMENTO', 'AJUDANTE', 22, null, 'reprovado', null, null, null),
  ('ROBSON DOS SANTOS ROCHA', 'MARTELETEIRO', 33, null, 'reprovado', null, null, null),
  ('BISMARC OLIVEIRA DE ALCANTARA', 'RASTELEIRO', 33, 'Thiago Silva', 'aprovado', 'aceita como ajudante', null, null),
  ('FAGNER SOUSA SANTOS', 'AJUDANTE', 42, null, 'reprovado', null, null, null),
  ('HENRIQUE ALBERTO', 'MANGUEIRISTA', 26, null, 'aprovado', 'aceita como ajudante', null, null),
  ('CARLOS ALBERTO JACINTO', 'MOTORISTA DE CAMINHÃO', 54, 'Geisson', 'aprovado', null, null, null),
  ('DOUGLAS LIMA DA SILVA', 'AJUDANTE', 41, 'Francisco Alves', 'aprovado', null, null, null),
  ('VITOR AUGUSTO DA SILVA', 'RASTELEIRO', 23, 'Aelson', 'reprovado', 'filho do luciano', 'filho do luciano', null),
  ('ALOIZIO DA SILVA', 'MOTORISTA BASCULANTE', 42, null, 'aprovado', 'Flag planilha: Fazer teste', null, null),
  ('FRANCISCO APARECIDO', 'MOTORISTA DE CAMINHÃO', 53, null, 'aprovado', null, null, null),
  ('PEDRO REINAN DA SILVA', 'MANGUEIRISTA', 26, null, 'aprovado', null, null, null),
  ('CLAYTON DA SILVA NUNES', 'ENGENHEIRO CIVIL', null, null, 'triagem', 'Marcar com o Tiago', null, null),
  ('CAIO VINICIUS DE ALMEIDA', 'AJUDANTE', 26, null, 'reprovado', null, null, null),
  ('ANDERSON HENRIQUE DE SOUSA', 'OPERADOR DE RETRO', 45, null, 'triagem', 'identificar p saiu de GRU, Opera Pa carregadeira, Dirige caminhão', null, null),
  ('JEFERSON BRENE', 'AJUDANTE', 23, 'Eudes', 'aprovado', null, null, null),
  ('NELSON ZEGGIO FILHO', 'MOTORISTA DE CAMINHÃO', 58, 'Magnus zeggio (irmão)', 'reprovado', null, null, null),
  ('MARCOS FERREIRA', 'OP DE BOBCAT', null, null, 'triagem', 'dirige caminhões', null, null),
  ('ERIC ALVES DE LIMA', 'AJUDANTE', 18, 'Antonio Carlos - Rolo', 'aprovado', null, null, null),
  ('LUCAS NORBERTO', 'MANGUEIRISTA', 28, 'Josenildo Raposa', 'aprovado', null, null, null),
  ('CLAUDINEI FRANCISCO', 'MOTORISTA BASCULANTE', 51, 'Josenildo Raposa', 'aprovado', 'não precisa fazer teste', null, null),
  ('RONILDO FRANCISCO', 'OP DE ESCAVADEIRA', null, null, 'reprovado', null, null, null)
)
select status_candidatura, count(*) as quantidade
from origem
group by status_candidatura
order by status_candidatura;

with origem(nome, funcao, idade, indicacao, status_candidatura, observacoes, motivo_reprovacao, resultado_teste) as (
  values
  ('ARNALDO FERREIRA', 'ENCARREGADO DE OBRAS', null, null, 'aprovado', 'Trabalha como operador em GRU', null, null),
  ('JOSÉ VALDIR', 'RASTELEIRO', null, 'Ricardo Barbieri', 'aprovado', 'já trabalhou na Fremix', null, null),
  ('FABIO ALMEIDA', 'MESISTA', null, 'Ricardo Barbieri', 'aprovado', 'já trabalhou na Fremix', null, null),
  ('FERNANDO SILVA GOMES', 'APONTADOR DE OBRAS', 40, null, 'reprovado', 'já trabalhou na Fremix', 'já trabalhou na Fremix', null),
  ('EDSON SERRANO', 'MOTORISTA BASCULANTE', 54, null, 'aprovado', 'ja trabalhou com diversos caminhões | Flag planilha: Fazer teste', null, null),
  ('RITERIS JOSÉ SILVA SOUZA', 'MOTORISTA DE CAMINHÃO', 46, null, 'aprovado', 'Onibus, Moop, Coletivo, faculdade de Logistica trancada | Flag planilha: Fazer teste', null, null),
  ('ADEILDO XAVIER DA SILVA', 'OPERADOR DE VIBRO', 51, 'Luciano op de Rolo', 'reprovado', 'saiu da Schunk porque não fazia horas extras', 'saiu da Schunk porque não fazia horas extras', null),
  ('FERNANDO JOSÉ SILVA', 'OP DE PA CARREGADEIRA', 39, null, 'aprovado', null, null, null),
  ('OTÁVIO OLIVEIRA SILVA', 'MANGUEIRISTA', 38, null, 'aprovado', 'Já trabalhou na Fremix (Aelson)', null, null),
  ('IGO DUARTE DE SOUSA', 'MOTORISTA DE CAMINHÃO', 37, 'Willy (irmão)', 'reprovado', null, null, null),
  ('LEIS PEREIRA', 'AJUDANTE', 41, 'Willian', 'reprovado', null, null, null),
  ('MAURICIO PEREIRA DA SILVA', 'MOTORISTA DE CAMINHÃO', 52, null, 'reprovado', 'já trabalhou na Fremix', 'já trabalhou na Fremix', null),
  ('JOSELITO JOSE DE SOUSA', 'RASTELEIRO', 58, null, 'aprovado', 'Muito experiente', null, null),
  ('FABIO PEREIRA BRITO', 'MOTORISTA DE CAMINHÃO', 39, 'Gustavo', 'reprovado', 'já trabalhou na Fremix', 'já trabalhou na Fremix', null),
  ('MARCOS DE FREITAS', 'AJUDANTE', 48, null, 'aprovado', null, null, null),
  ('JEFFERSSON SALES TEIXEIRA', 'AJUDANTE', 39, null, 'reprovado', 'Já trabalhou na Usivix', 'Já trabalhou na Usivix', null),
  ('KHEVYN BRYAN GARCIA', 'AJUDANTE', 18, 'Jailson (Padrastro)', 'reprovado', null, null, null),
  ('CHARLI BARBOSA AZEVEDO', 'OPERADOR DE MAQUINAS', 36, null, 'aprovado', 'Trabalhou em GRU - Opera diversas maquinas', null, null),
  ('FELIPE CARVALHO CAMILO', 'AJUDANTE', null, 'Plinio (Técnico)', 'reprovado', null, null, null),
  ('DAVI CARLOS SILVA MENDES', 'AJUDANTE', 28, 'Plinio (Técnico)', 'reprovado', null, null, null),
  ('HAZIELL ALVES NOGUEIRA', 'AJUDANTE', 27, 'Eurismar', 'aprovado', null, null, null),
  ('JORGE SANTOS DE OLIVEIRA', 'OPERADOR DE MAQUINAS', 47, null, 'reprovado', 'CNH AB provisória', 'CNH AB provisória', null),
  ('CICERO RICARDO SOUZA', 'OP DE BOBCAT', null, null, 'triagem', null, null, null),
  ('ALVARO MOREIRA DOS SANTOS', 'AJUDANTE', 38, null, 'aprovado', 'já foi apontador / Rasteleiro', null, null),
  ('VICTOR AUGUSTO DO NASCIMENTO', 'RASTELEIRO', 37, null, 'aprovado', null, null, null),
  ('GUTEMBERGUE PEREIRA FELIX', 'OP DE BOBCAT', 34, 'Gilberto (op de bobcat)', 'aprovado', 'Também é Motorista | Flag planilha: Fazer teste', null, null),
  ('JOSINALDO FERREIRA BARROS', 'MOTORISTA BASCULANTE', 48, null, 'aprovado', 'Flag planilha: Fazer teste', null, null),
  ('FELIPE PEREIRA NEPONUCEMO', 'APONTADOR DE OBRAS', 21, 'Alan (Técnico de Segurança)', 'reprovado', null, null, null),
  ('MATHEUS VINICIUS CAMPO', 'AJUDANTE', 24, null, 'aprovado', 'já trabalhou na Fremix / tem experiancia de apontador na FBS)', null, null),
  ('JOVANILSON PEREIRA GOMES', 'RASTELEIRO', 35, 'Thiago Silva', 'aprovado', 'já trabalhou na Fremix', null, null),
  ('ILDEU APARECIDO DOS REIS', 'RASTELEIRO', 60, null, 'aprovado', 'já trabalhou na Fremix', null, null),
  ('WALTER RODRIGUES DE AGUIAR', 'MOTORISTA BASCULANTE', 53, null, 'aprovado', null, null, null),
  ('RONALDO BARBOSA DE LUCENA', 'OPERADOR DE VIBRO', 49, null, 'aprovado', 'já trabalhou na Fremix / atualmente na FBS', null, null),
  ('MARCELO ARAUJO DE SOUZA', 'OP DE ROLO', 45, null, 'aprovado', 'Flag planilha: Fazer teste', null, null),
  ('MARCOS ANTONIO DA SOUZA', 'MESISTA', 25, 'Francisco Patricio', 'aprovado', null, null, null),
  ('CICERO DANRLEY CARVALHO SOUZA', 'AJUDANTE', 29, 'Jose Cicero', 'aprovado', null, null, null),
  ('JANDERSON RYAN SILVA DOS SANTOS', 'AJUDANTE', 24, 'Geandson', 'reprovado', 'já trabalhou na Fremix / Thiago Silva', 'já trabalhou na Fremix / Thiago Silva', null),
  ('JAMES DE ALMEIDA BARBOSA', 'MOTORISTA CARRETEIRO', 43, 'Ricardo Nobre', 'aprovado', 'experiente em caçamba | Flag planilha: Fazer teste', null, null),
  ('MARCOS TADEU DE OLIVEIRA', 'AJUDANTE', 37, 'Gustavo', 'aprovado', null, null, null),
  ('MANUEL MARCOLINO MACHADO', 'RASTELEIRO', 39, 'Max Alan', 'aprovado', null, null, null),
  ('JOSE ARNALDO GUILHERME', 'RASTELEIRO', 53, 'Davi Carlos', 'aprovado', null, null, null),
  ('MANOEL SILVA SANTOS', 'OPERADOR DE VIBRO', 34, null, 'aprovado', 'Flag planilha: Fazer teste', null, null),
  ('UOZITON MANOEL GOMES', 'OPERADOR DE VIBRO', 38, null, 'aprovado', 'já trabalhou como encarregado, opera todas as maquinas de pavimentação menos fresa | Flag planilha: Fazer teste', null, null),
  ('DANILO THOMAZ D URBANO', 'OP DE BOBCAT', 36, 'Aila', 'aprovado', null, null, null),
  ('ALEXSANDRO DOS SANTOS RODRIGUES', 'AJUDANTE', 34, 'Jailson', 'aprovado', 'Soldador', null, null),
  ('RENILDO OLIVEIRA MOREIRA', 'AJUDANTE', 29, null, 'triagem', 'já trabalhou na Fremix', null, null),
  ('JOSÉ DA SILVA LIMA', 'MOTORISTA BASCULANTE', 62, null, 'teste', 'Flag planilha: Fazer teste', null, 'PENDENTE'),
  ('MARIVALDO EVANGELISTA DE SOUZA', 'AJUDANTE', 35, 'Jose Cicero', 'aprovado', null, null, null),
  ('DENIS DE PAULA MACHADO', 'AJUDANTE', 34, 'Jose Cicero', 'aprovado', null, null, null),
  ('EDINALDO DE OLIVEIRA', 'MOTORISTA DE CAMINHÃO', 43, null, 'aprovado', 'Flag planilha: Fazer teste', null, null),
  ('HERICLES ARAUJO DE SOUZA', 'AJUDANTE', 31, 'Fabio', 'aprovado', null, null, null),
  ('ROGERIO DAS NEVES COSTA', 'MOTORISTA ONIBUS', 46, 'André Luiz', 'aprovado', 'Flag planilha: Fazer teste', null, null),
  ('JOÃO RICARDO DA SILVA', 'MOTORISTA CARRETEIRO', 56, null, 'reprovado', null, null, null),
  ('KELVIN DA SILVA BARBOSA', 'AJUDANTE', 26, 'Rafael Pinheiro', 'reprovado', null, null, null),
  ('KAIQUE SOUSA', 'OPERADOR DE VIBRO', 33, 'Rafael Pinheiro', 'aprovado', 'Flag planilha: Fazer teste', null, null),
  ('ARTUR SUDARIO DE ASSIS', 'AJUDANTE', 29, 'Plinio (Técnico)', 'aprovado', 'Esposa Gravida', null, null),
  ('JOÃO ROMANATO', 'MOTORISTA DE CAMINHÃO', 52, 'Wilson', 'aprovado', null, null, null),
  ('SAMUEL SANTOS AZEVEDO', 'MOTORISTA DE CAMINHÃO', 40, 'José Hilton', 'aprovado', null, null, null),
  ('LUIZ ANTONIO DOS SANTOS SILVA', 'MOTORISTA BASCULANTE', 53, 'Alexandre - Contabilidade', 'aprovado', null, null, null),
  ('CARLOS EDUARDO DA SILVA', 'RASTELEIRO', 43, null, 'aprovado', null, null, null),
  ('ROMILDO ALVES PEREIRA', 'MOTORISTA DE CAMINHÃO', 71, null, 'aprovado', null, null, null),
  ('FELIPE FRANCISCO ALVES', 'AJUDANTE', 27, 'Cleder / Plinio', 'reprovado', null, null, null),
  ('DIEGO JONE RODRIGUES', 'AJUDANTE', 33, null, 'aprovado', null, null, null),
  ('WHASHINGTON DO CARMO MELO', 'AJUDANTE', 40, 'Eurismar', 'aprovado', null, null, null),
  ('BRUNO EDUARDO F DE MATOS', 'MOTORISTA DE CAMINHÃO', 31, null, 'aprovado', 'Trabalhou na Fremix - Comboio', null, null),
  ('ROGÉRIO FERREIRA SANTANA', 'AJUDANTE', 23, 'Rodrigo / Geisson', 'aprovado', null, null, null),
  ('JOÃO PAULO CASSIANO', 'APONTADOR DE OBRAS', 38, 'Gabriel Evaristo', 'aprovado', 'Apontador de Infra, Formado em Tec. Edificações', null, null),
  ('CARLOS HENRIQUE MONTEIRO', 'TEC DE SEGURANÇA', 54, null, 'reprovado', null, null, null),
  ('WILLIN GABRIEL NASCIMENTO', 'AJUDANTE', 22, null, 'reprovado', null, null, null),
  ('ROBSON DOS SANTOS ROCHA', 'MARTELETEIRO', 33, null, 'reprovado', null, null, null),
  ('BISMARC OLIVEIRA DE ALCANTARA', 'RASTELEIRO', 33, 'Thiago Silva', 'aprovado', 'aceita como ajudante', null, null),
  ('FAGNER SOUSA SANTOS', 'AJUDANTE', 42, null, 'reprovado', null, null, null),
  ('HENRIQUE ALBERTO', 'MANGUEIRISTA', 26, null, 'aprovado', 'aceita como ajudante', null, null),
  ('CARLOS ALBERTO JACINTO', 'MOTORISTA DE CAMINHÃO', 54, 'Geisson', 'aprovado', null, null, null),
  ('DOUGLAS LIMA DA SILVA', 'AJUDANTE', 41, 'Francisco Alves', 'aprovado', null, null, null),
  ('VITOR AUGUSTO DA SILVA', 'RASTELEIRO', 23, 'Aelson', 'reprovado', 'filho do luciano', 'filho do luciano', null),
  ('ALOIZIO DA SILVA', 'MOTORISTA BASCULANTE', 42, null, 'aprovado', 'Flag planilha: Fazer teste', null, null),
  ('FRANCISCO APARECIDO', 'MOTORISTA DE CAMINHÃO', 53, null, 'aprovado', null, null, null),
  ('PEDRO REINAN DA SILVA', 'MANGUEIRISTA', 26, null, 'aprovado', null, null, null),
  ('CLAYTON DA SILVA NUNES', 'ENGENHEIRO CIVIL', null, null, 'triagem', 'Marcar com o Tiago', null, null),
  ('CAIO VINICIUS DE ALMEIDA', 'AJUDANTE', 26, null, 'reprovado', null, null, null),
  ('ANDERSON HENRIQUE DE SOUSA', 'OPERADOR DE RETRO', 45, null, 'triagem', 'identificar p saiu de GRU, Opera Pa carregadeira, Dirige caminhão', null, null),
  ('JEFERSON BRENE', 'AJUDANTE', 23, 'Eudes', 'aprovado', null, null, null),
  ('NELSON ZEGGIO FILHO', 'MOTORISTA DE CAMINHÃO', 58, 'Magnus zeggio (irmão)', 'reprovado', null, null, null),
  ('MARCOS FERREIRA', 'OP DE BOBCAT', null, null, 'triagem', 'dirige caminhões', null, null),
  ('ERIC ALVES DE LIMA', 'AJUDANTE', 18, 'Antonio Carlos - Rolo', 'aprovado', null, null, null),
  ('LUCAS NORBERTO', 'MANGUEIRISTA', 28, 'Josenildo Raposa', 'aprovado', null, null, null),
  ('CLAUDINEI FRANCISCO', 'MOTORISTA BASCULANTE', 51, 'Josenildo Raposa', 'aprovado', 'não precisa fazer teste', null, null),
  ('RONILDO FRANCISCO', 'OP DE ESCAVADEIRA', null, null, 'reprovado', null, null, null)
)
select *
from origem
order by nome
limit 20;
