with names(name) as (
  values
  ('ALMIR JOSÉ DA SILVA'),
  ('ALMIR JOSÉ DA SILVA SANTOS'),
  ('ANTONIO DIEGO SILVA DE OLIVEIRA'),
  ('ANTONIO TIAGO PEREIRA GOMES'),
  ('BARBARA NICOLI DOS SANTOS DUARTE'),
  ('CAIO MULLER'),
  ('CARLOS SANTOS DA SILVA'),
  ('CLESSIO LUCENA DE CARVALHO'),
  ('DANIEL PEREIRA DA SILVA'),
  ('DOMINGOS CRUZ SANTANA'),
  ('EDUARDO SANTOS DE SOUZA'),
  ('ELIEZER - VIGENT'),
  ('IRLAN SANTOS FERREIRA'),
  ('JOEL GONÇALVES'),
  ('JOSÉ AILTON QUIRINO DOS SANTOS'),
  ('KAECIO MATIAS MINERVINO'),
  ('KLESSIO LUCENA DE CARVALHO'),
  ('LUCAS CORREIA XAVIER DE JESUS'),
  ('LUIZ CARLOS LOPES ARRUDA DA SILVA'),
  ('LUIZ EDUARDO'),
  ('LUIZ HENRIQUE LOPES DA SILVA'),
  ('MIKAEL ALVES SILVA'),
  ('PAULINHO JESUS DE OLIVEIRA'),
  ('PAULO RICARDO SOUZA GUIMARÃES'),
  ('ROMILDO FREIRE MARTINS'),
  ('VICTOR GUEDES LEMOS'),
  ('VINICIUS DOS SANTOS'),
  ('WALLA WILLIAM DA SILVA NEVES'),
  ('EDMAR GOULART SILVA'),
  ('GILDO VIEIRA MANCO'),
  ('IVANILSON ANDRADE DA SILVA'),
  ('MAURICIO PEREIRA SALVIANO'),
  ('EDJA DOS SANTOS LOPES'),
  ('ALAN DE FREITAS SANTOS'),
  ('ALEXSANDRO GARCIA'),
  ('ALYSSON PETRÔNIO'),
  ('BRUNNO MAGALHÃES'),
  ('DIMAS IBIAPINA'),
  ('ELCIO FERREIRA'),
  ('GABRIEL EVARISTO'),
  ('GEISSON MARTINS FELICIANO'),
  ('LUCAS BARBOSA'),
  ('RAFAEL VIEIRA'),
  ('SIDNEI FERREIRA'),
  ('VITOR COLASSIO'),
  ('PLINIO MOREIRA'),
  ('DIEGO VALE'),
  ('JADISON DA SILVA VICENTE'),
  ('DANILO THOMAS DO N URBANO'),
  ('CLAUDIO MIRANDA DA SILVA'),
  ('ROGERIO DE SANTANA'),
  ('WENER DA SILVA VERENOZ'),
  ('JEFFERSON MARTINS FELICIANO'),
  ('RICARDO NOBRE DA SILVA'),
  ('GILBERTO VIDAL ALVES'),
  ('JOAO ALMEIDA DE SOUSA'),
  ('GENESIO VENANCIO GIMENES'),
  ('REGILNALDO PEREIRA DE ANDRADE'),
  ('FABIO SILVA DOS SANTOS'),
  ('GERFFESSON RODRIGUES SANTOS'),
  ('ANDERSON MARQUES SANTANA'),
  ('VITOR MAÇAL COLASSIO'),
  ('ELCIMAR ALCINO DA SILVA'),
  ('ALLAN FREITAS'),
  ('IGOR CAPUCHO'),
  ('GERALDO JOSE DOS SANTOS'),
  ('JAELESON MAURICIO VIEIRA'),
  ('PAULO JESUS DE OLIVEIRA')
),
rdo_p as (select upper(trim(preenchido_por)) as nm, count(*) as c, min(data) as dmin, max(data) as dmax from rdo_diarios where company_id='a1b2c3d4-e5f6-7890-abcd-ef1234567890' and preenchido_por is not null and trim(preenchido_por)<>'' group by 1),
rdo_r as (select upper(trim(responsavel)) as nm, count(*) as c, min(data) as dmin, max(data) as dmax from rdo_diarios where company_id='a1b2c3d4-e5f6-7890-abcd-ef1234567890' and responsavel is not null and trim(responsavel)<>'' group by 1),
rdo_e as (select upper(trim(encarregado)) as nm, count(*) as c, min(data) as dmin, max(data) as dmax from rdo_diarios where company_id='a1b2c3d4-e5f6-7890-abcd-ef1234567890' and encarregado is not null and trim(encarregado)<>'' group by 1),
eq_o as (select upper(trim(operator_name)) as nm, count(*) as c, min(date) as dmin, max(date) as dmax from equipment_diaries where company_id='a1b2c3d4-e5f6-7890-abcd-ef1234567890' and operator_name is not null and trim(operator_name)<>'' group by 1),
eq_s as (select upper(trim(operator_solo)) as nm, count(*) as c, min(date) as dmin, max(date) as dmax from equipment_diaries where company_id='a1b2c3d4-e5f6-7890-abcd-ef1234567890' and operator_solo is not null and trim(operator_solo)<>'' group by 1)
select n.name,
  coalesce(rp.c,0) as rdo_preenchido_por,
  coalesce(rr.c,0) as rdo_responsavel,
  coalesce(re.c,0) as rdo_encarregado,
  coalesce(eo.c,0) as eq_operator_name,
  coalesce(es.c,0) as eq_operator_solo,
  (coalesce(rp.c,0)+coalesce(rr.c,0)+coalesce(re.c,0)+coalesce(eo.c,0)+coalesce(es.c,0)) as total_refs,
  least(coalesce(rp.dmin,'9999-12-31'::date),coalesce(rr.dmin,'9999-12-31'::date),coalesce(re.dmin,'9999-12-31'::date),coalesce(eo.dmin,'9999-12-31'::date),coalesce(es.dmin,'9999-12-31'::date)) as primeira_data,
  greatest(coalesce(rp.dmax,'1900-01-01'::date),coalesce(rr.dmax,'1900-01-01'::date),coalesce(re.dmax,'1900-01-01'::date),coalesce(eo.dmax,'1900-01-01'::date),coalesce(es.dmax,'1900-01-01'::date)) as ultima_data
from names n
left join rdo_p rp on upper(trim(n.name))=rp.nm
left join rdo_r rr on upper(trim(n.name))=rr.nm
left join rdo_e re on upper(trim(n.name))=re.nm
left join eq_o eo on upper(trim(n.name))=eo.nm
left join eq_s es on upper(trim(n.name))=es.nm
order by total_refs desc, n.name;
