
-- Remap BOBCAT and FRESADORA from GRANDE PORTE to FRESA/BOB
UPDATE maquinas_frota SET categoria = 'FRESA/BOB' WHERE tipo IN ('FRESADORA', 'BOBCAT');

-- Remap ROLO CHAPA, ROLO PNEU, VIBRO ACABADORA, ROLO PÉ DE CARNEIRO to VIBRO/ROLO
UPDATE maquinas_frota SET categoria = 'VIBRO/ROLO' WHERE tipo IN ('ROLO CHAPA', 'ROLO PNEU', 'VIBRO ACABADORA', 'ROLO PÉ DE CARNEIRO');

-- Remap RETROESCAVADEIRA to LINHA AMARELA
UPDATE maquinas_frota SET categoria = 'LINHA AMARELA' WHERE tipo = 'RETROESCAVADEIRA';

-- Remap USINA MÓVEL to USINAGEM
UPDATE maquinas_frota SET categoria = 'USINAGEM' WHERE tipo = 'USINA MÓVEL';
