-- Limpar tabela de funcionários e reinserir lista atualizada
DELETE FROM public.funcionarios;

INSERT INTO public.funcionarios (nome, funcao, matricula) VALUES
-- AJUDANTE DE MECANICA
('LINDOMAR DOS REIS FARIA', 'AJUDANTE DE MECANICA', 'F001'),

-- AJUDANTE GERAL (alfabético)
('ABNER ENZO AMORIM DE FARIAS', 'AJUDANTE GERAL', 'F002'),
('ANDERSON EUCLIDES DOS REIS', 'AJUDANTE GERAL', 'F003'),
('ANDERSON GONÇALVES CORREA', 'AJUDANTE GERAL', 'F004'),
('ANDRE ALMEIDA B DA SILVA', 'AJUDANTE GERAL', 'F005'),
('ANDRE DE CARVALHO LEITE', 'AJUDANTE GERAL', 'F006'),
('ANDRE RODRIGUES REIS', 'AJUDANTE GERAL', 'F007'),
('ANTONIO FERNANDO DE SOUZA', 'AJUDANTE GERAL', 'F008'),
('ANTONIO JOSE DA SILVA', 'AJUDANTE GERAL', 'F009'),
('AURELIO PAIVA E SILVA', 'AJUDANTE GERAL', 'F010'),
('BRUNO SANTOS E SILVA', 'AJUDANTE GERAL', 'F011'),
('CAIO LUIZ TOMAZ DA SILVA', 'AJUDANTE GERAL', 'F012'),
('CESAR OLIVEIRA BARBOSA', 'AJUDANTE GERAL', 'F013'),
('CHRISTIAN EDUARDO C SILVA', 'AJUDANTE GERAL', 'F014'),
('CLAUDIONEI MATIAS DOS S JUNIOR', 'AJUDANTE GERAL', 'F015'),
('CLEBER AMARAL DOS SANTOS', 'AJUDANTE GERAL', 'F016'),
('CLEDER AVACI DE SOUSA', 'AJUDANTE GERAL', 'F017'),
('CLEITON ALMEIDA DA SILVA', 'AJUDANTE GERAL', 'F018'),
('CRISTIAN GOMES DE SOUSA', 'AJUDANTE GERAL', 'F019'),
('CRISTIANO PAULO DA SILVA', 'AJUDANTE GERAL', 'F020'),
('DARLEI SOUZA SANTOS', 'AJUDANTE GERAL', 'F021'),
('DEIVID GUSTAVO P MARQUES', 'AJUDANTE GERAL', 'F022'),
('DILERMANDO REIS FERNANDES', 'AJUDANTE GERAL', 'F023'),
('DOUGLAS A DE JESUS BANDEIRA', 'AJUDANTE GERAL', 'F024'),
('DOUGLAS NASCIMENTO RUFO', 'AJUDANTE GERAL', 'F025'),
('EDMAR GOULART SILVA', 'AJUDANTE GERAL', 'F026'),
('EDSON CARLOS DE FREITAS', 'AJUDANTE GERAL', 'F027'),
('EDSON DA SILVA SILVEIRA', 'AJUDANTE GERAL', 'F028'),
('EDSON ROCHA RODRIGUES JUNIOR', 'AJUDANTE GERAL', 'F029'),
('EDUARDO DIAS CARDOSO', 'AJUDANTE GERAL', 'F030'),
('ELCIMAR ALCINO DA SILVA', 'AJUDANTE GERAL', 'F031'),
('EMERSON CARLOS DO NASCIMENTO', 'AJUDANTE GERAL', 'F032'),
('ERALDO EDINALDO DOS SANTOS', 'AJUDANTE GERAL', 'F033'),
('EURISMAR ALVES DE MOURA', 'AJUDANTE GERAL', 'F034'),
('FELIPE CARVALHO CAMILO', 'AJUDANTE GERAL', 'F035'),
('FLAVIO PAES LANDIM DOS SANTOS', 'AJUDANTE GERAL', 'F036'),
('GENIZAN GENERINO D DOS SANTOS', 'AJUDANTE GERAL', 'F037'),
('GUILHERME EUGENIO MONTEIRO', 'AJUDANTE GERAL', 'F038'),
('IGOR MICHAEL M A DO AMORIM', 'AJUDANTE GERAL', 'F039'),
('ISAEL DO AMARAL FERREIRA', 'AJUDANTE GERAL', 'F040'),
('IVANILSON ANDRADE DA SILVA', 'AJUDANTE GERAL', 'F041'),
('IZAIAS VIANA DE JESUS', 'AJUDANTE GERAL', 'F042'),
('JADISON DA SILVA VICENTE', 'AJUDANTE GERAL', 'F043'),
('JASON ROBERTO DOS SANTOS', 'AJUDANTE GERAL', 'F044'),
('JHONATAN MARTINS DA SILVA', 'AJUDANTE GERAL', 'F045'),
('JOAO PAULO FERREIRA DOS SANTOS', 'AJUDANTE GERAL', 'F046'),
('JOAO VICTOR DA S OLIVEIRA', 'AJUDANTE GERAL', 'F047'),
('JOHNI CESAR G DE OLIVEIRA', 'AJUDANTE GERAL', 'F048'),
('JONATHAN APARECIDO P MARQUES', 'AJUDANTE GERAL', 'F049'),
('JOSE EDIMILSON P DA SILVA', 'AJUDANTE GERAL', 'F050'),
('KAIQUE REIS COSTA', 'AJUDANTE GERAL', 'F051'),
('KAUE MATHEUS FERREIRA', 'AJUDANTE GERAL', 'F052'),
('LEANDRO VALENTIN TEIXEIRA', 'AJUDANTE GERAL', 'F053'),
('LUIS GUSTAVO ALVES SILVA', 'AJUDANTE GERAL', 'F054'),
('MARCO AURELIO G DOS SANTOS', 'AJUDANTE GERAL', 'F055'),
('MARCOS HENRIQUE M DE S SANTANA', 'AJUDANTE GERAL', 'F056'),
('MARCOS PAULO C DO AMARAL', 'AJUDANTE GERAL', 'F057'),
('MARIO HENRIQUE S DE OLIVEIRA', 'AJUDANTE GERAL', 'F058'),
('MATHEUS MADERSON DOS SANTOS', 'AJUDANTE GERAL', 'F059'),
('MAURICIO PEREIRA SALVIANO', 'AJUDANTE GERAL', 'F060'),
('MESSIAS DE SOUZA SILVEIRA', 'AJUDANTE GERAL', 'F061'),
('PEDRO HENRIQUE M F DOS SANTOS', 'AJUDANTE GERAL', 'F062'),
('RAFAEL DAVID M DOS SANTOS', 'AJUDANTE GERAL', 'F063'),
('ROBERIO SANTOS OLIVEIRA', 'AJUDANTE GERAL', 'F064'),
('SAMUEL ALVES COSTA', 'AJUDANTE GERAL', 'F065'),
('VALMIR SANTOS MOREIRA JUNIOR', 'AJUDANTE GERAL', 'F066'),

-- AMOXARIFE JR I
('MARCOS PAULO FERREIRA MELO', 'AMOXARIFE JR I', 'F067'),

-- ANALISTA DE RH JR
('SANDRA PAULA DE OLIVEIRA', 'ANALISTA DE RH JR', 'F068'),

-- APONTADOR DE OBRAS (alfabético)
('ADILSON CARLOS R DOS SANTOS', 'APONTADOR DE OBRAS', 'F069'),
('ALAN KARDEC CARVALHO MOREIRA', 'APONTADOR DE OBRAS', 'F070'),
('ALEX SILVA DOS SANTOS', 'APONTADOR DE OBRAS', 'F071'),
('CAIQUE ARON ALENCAR DA SILVA', 'APONTADOR DE OBRAS', 'F072'),
('DAVI CARLOS RIBEIRO', 'APONTADOR DE OBRAS', 'F073'),
('DIEGO SIPRIANO SANTOS DE JESUS', 'APONTADOR DE OBRAS', 'F074'),
('DOUGLAS ALVES DE OLIVEIRA', 'APONTADOR DE OBRAS', 'F075'),
('FRANCISCO ALVES JUNIOR', 'APONTADOR DE OBRAS', 'F076'),
('JOSE AMARO DE BRITO BATISTA', 'APONTADOR DE OBRAS', 'F077'),
('LUIZ HENRIQUE DA SILVA', 'APONTADOR DE OBRAS', 'F078'),
('MICHAEL CUNHA DOS SANTOS', 'APONTADOR DE OBRAS', 'F079'),
('RODRIGO FERREIRA', 'APONTADOR DE OBRAS', 'F080'),
('RONILTON DE SOUSA PEREIRA', 'APONTADOR DE OBRAS', 'F081'),
('TALES HENRIQUE NUNES PEREIRA', 'APONTADOR DE OBRAS', 'F082'),
('VALDENI DIAS QUEIROZ', 'APONTADOR DE OBRAS', 'F083'),
('WILLIAM SILVA SEBASTIAO', 'APONTADOR DE OBRAS', 'F084'),
('WILLY DUARTE FREITAS', 'APONTADOR DE OBRAS', 'F085'),

-- ASS. ADM. (alfabético)
('DALILA PRISCILLA GONCALVES', 'ASS. ADM.', 'F086'),
('EDUARDO PEREIRA DA S JUNIOR', 'ASS. ADM.', 'F087'),
('ISABELA PAIXÃO ARAUJO', 'ASS. ADM.', 'F088'),

-- DESENHISTA TECNICO
('ADALBERTO SILVA MALAQUIAS', 'DESENHISTA TECNICO', 'F089'),

-- ENCARREDADO DE INFRA (alfabético)
('JONATHAN RUBENS GOMES', 'ENCARREDADO DE INFRA', 'F090'),
('LUIZ GONZAGA DA SILVA MELO', 'ENCARREDADO DE INFRA', 'F091'),

-- ENCARREGADO DE OBRAS (alfabético)
('AELSON ROMEU COUTINHO', 'ENCARREGADO DE OBRAS', 'F092'),
('DANIEL BRUNO BRITO', 'ENCARREGADO DE OBRAS', 'F093'),
('GIVANILDO BATISTA ESTEVAO', 'ENCARREGADO DE OBRAS', 'F094'),
('JHONATHAN WARICK DE FIGUEIREDO', 'ENCARREGADO DE OBRAS', 'F095'),
('JOSENILDO DA SILVA RAMOS', 'ENCARREGADO DE OBRAS', 'F096'),
('THIAGO HENRIQUE F PIMENTEL', 'ENCARREGADO DE OBRAS', 'F097'),
('THIAGO SILVA DOS SANTOS', 'ENCARREGADO DE OBRAS', 'F098'),
('VITOR MAÇAL COLASSIO', 'ENCARREGADO DE OBRAS', 'F099'),

-- ENGENHEIRO CIVIL (alfabético)
('ALAN DE FREITAS SANTOS', 'ENGENHEIRO CIVIL', 'F100'),
('ALEXSANDRO ANTONIO GARCIA', 'ENGENHEIRO CIVIL', 'F101'),
('ALYSSON PETRÔNIO CORREIA SILVA', 'ENGENHEIRO CIVIL', 'F102'),
('DIMAS DE SOUZA IBIAPINA', 'ENGENHEIRO CIVIL', 'F103'),
('ELCIO FRANCISCO FERREIRA JUNIOR', 'ENGENHEIRO CIVIL', 'F104'),
('GABRIEL DOS SANTOS EVARISTO', 'ENGENHEIRO CIVIL', 'F105'),
('LUCAS DE ARAUJO BARBOSA', 'ENGENHEIRO CIVIL', 'F106'),

-- MANGUEIRISTA (alfabético)
('LEANDRO SILVA RIBEIRO', 'MANGUEIRISTA', 'F107'),
('LUA SILVA SANTOS', 'MANGUEIRISTA', 'F108'),
('MARCOS ANTONIO DOS SANTOS', 'MANGUEIRISTA', 'F109'),
('RICHARD DA SILVA ELIAS', 'MANGUEIRISTA', 'F110'),
('WERGLEI ALVES DE SOUZA', 'MANGUEIRISTA', 'F111'),

-- MARTELETEIRO (alfabético)
('DANIEL FERREIRA', 'MARTELETEIRO', 'F112'),
('JOSE ANDRE OLIVEIRA DA SILVA', 'MARTELETEIRO', 'F113'),
('MARCOS AURELIO B LAURINDO', 'MARTELETEIRO', 'F114'),
('RODRIGO XAVIER DE LIMA', 'MARTELETEIRO', 'F115'),

-- MECANICO DE MAQUINA
('MARCOS ANTONIO S DOS SANTOS', 'MECANICO DE MAQUINA', 'F116'),

-- MESISTA (alfabético)
('LUIZ CARLOS COSTA DOS SANTOS', 'MESISTA', 'F117'),
('MATHEUS MANOEL P M DOS SANTOS', 'MESISTA', 'F118'),
('RYAN CLEITON DELFINO PEQUENO', 'MESISTA', 'F119'),
('SAMUEL VIEIRA BARBOSA MARTINS', 'MESISTA', 'F120'),
('THIAGO OLIVEIRA SANTOS', 'MESISTA', 'F121'),

-- MOTORISTA CAMINHAO (alfabético)
('JOSE HELENO DE P F SILVA', 'MOTORISTA CAMINHAO', 'F122'),
('ROBSON JANUARIO DE OLIVEIRA', 'MOTORISTA CAMINHAO', 'F123'),

-- MOTORISTA CAMINHÃO BASCULANTE (alfabético)
('DEVALDO DE ARUJO LOPES', 'MOTORISTA CAMINHÃO BASCULANTE', 'F124'),
('DIEGO CIARALLO DE GODOI', 'MOTORISTA CAMINHÃO BASCULANTE', 'F125'),
('FERNANDO GABRIEL F DE OLIVEIRA', 'MOTORISTA CAMINHÃO BASCULANTE', 'F126'),
('JOSE ANTONIO TARESEVICINTE', 'MOTORISTA CAMINHÃO BASCULANTE', 'F127'),
('JOSE HILTON MONTEIRO', 'MOTORISTA CAMINHÃO BASCULANTE', 'F128'),
('MAGNUS ZEGGIO', 'MOTORISTA CAMINHÃO BASCULANTE', 'F129'),
('MAURICIO MARQUES', 'MOTORISTA CAMINHÃO BASCULANTE', 'F130'),
('RENATO SILVA RIBEIRO', 'MOTORISTA CAMINHÃO BASCULANTE', 'F131'),

-- MOTORISTA CAMINHÃO CARROCERIA (alfabético)
('ALAN CARLOS DA COSTA', 'MOTORISTA CAMINHÃO CARROCERIA', 'F132'),
('ALESSANDRO BORGES', 'MOTORISTA CAMINHÃO CARROCERIA', 'F133'),
('ANAILSON GIL SOUTO CARVALHO', 'MOTORISTA CAMINHÃO CARROCERIA', 'F134'),
('ANTONIO CARLOS DOS SANTOS', 'MOTORISTA CAMINHÃO CARROCERIA', 'F135'),
('CLEISON RIBEIRO ALVES', 'MOTORISTA CAMINHÃO CARROCERIA', 'F136'),
('JOAO TENORIO COSTA', 'MOTORISTA CAMINHÃO CARROCERIA', 'F137'),
('JONATHAS SANTANA DOS SANTOS', 'MOTORISTA CAMINHÃO CARROCERIA', 'F138'),
('JOSE CICERO DA SILVA IRMAO', 'MOTORISTA CAMINHÃO CARROCERIA', 'F139'),
('JOSE PAULO SANTOS', 'MOTORISTA CAMINHÃO CARROCERIA', 'F140'),
('LAZARO DE JESUS SANTOS', 'MOTORISTA CAMINHÃO CARROCERIA', 'F141'),
('SEVERINO ISIDRO DA SILVA', 'MOTORISTA CAMINHÃO CARROCERIA', 'F142'),

-- MOTORISTA CAMINHÃO PIPA (alfabético)
('JOAQUIM SILVA BESERRA', 'MOTORISTA CAMINHÃO PIPA', 'F143'),
('JOSE NILTON PEREIRA', 'MOTORISTA CAMINHÃO PIPA', 'F144'),
('JUCIGLAY DE ANDRADE RODRIGUES', 'MOTORISTA CAMINHÃO PIPA', 'F145'),
('LEANDRO PEREIRA DE OLIVEIRA', 'MOTORISTA CAMINHÃO PIPA', 'F146'),
('RAFAEL SILVA PINHEIRO', 'MOTORISTA CAMINHÃO PIPA', 'F147'),

-- MOTORISTA CARRETA (alfabético)
('DANILO SANTOS E SILVA', 'MOTORISTA CARRETA', 'F148'),
('HELENO CHAVES DE OLIVEIRA', 'MOTORISTA CARRETA', 'F149'),
('RICARDO NOBRE DA SILVA', 'MOTORISTA CARRETA', 'F150'),

-- MOTORISTA COMBOIO
('CELSO SANTANA P DE SOUZA', 'MOTORISTA COMBOIO', 'F151'),

-- MOTORISTA DE MICROÔNIBUS
('DOUGLAS CASEMIRO SCHWED', 'MOTORISTA DE MICROÔNIBUS', 'F152'),

-- MOTORISTA ESPARGIDOR (alfabético)
('CRISTIANO NERES DA ROCHA', 'MOTORISTA ESPARGIDOR', 'F153'),
('DANILO SATURNINO DE SOUZA', 'MOTORISTA ESPARGIDOR', 'F154'),
('GEANDSON ALEXANDRE DA SILVA', 'MOTORISTA ESPARGIDOR', 'F155'),
('JEFFERSON MARTINS FELICIANO', 'MOTORISTA ESPARGIDOR', 'F156'),
('MAGNUS HENRIQUE DE F ZEGGIO', 'MOTORISTA ESPARGIDOR', 'F157'),
('WELITON RODRIGUES DOS SANTOS', 'MOTORISTA ESPARGIDOR', 'F158'),

-- MOTORISTA VAN (alfabético)
('CLAUDIO MIRANDA DA SILVA', 'MOTORISTA VAN', 'F159'),
('JEISSON LUIZ VIEIRA VARRICHIO', 'MOTORISTA VAN', 'F160'),

-- OP DE BOBCAT (alfabético)
('EDSON BRUNO NUNES SANTOS', 'OP DE BOBCAT', 'F161'),
('GILBERTO VIDAL ALVES', 'OP DE BOBCAT', 'F162'),
('JOAO ALMEIDA DE SOUSA', 'OP DE BOBCAT', 'F163'),
('LUCIANO NEVES DE MEDEIROS', 'OP DE BOBCAT', 'F164'),
('ROGERLANDO RODRIGUES DOS SANTO', 'OP DE BOBCAT', 'F165'),
('TIAGO DE SOUSA PEREIRA', 'OP DE BOBCAT', 'F166'),
('WELLINGTON VELOZO J NASCIMENTO', 'OP DE BOBCAT', 'F167'),

-- OP DE ESCAVADEIRA (alfabético)
('CHARLI BARBOSA AZEVEDO', 'OP DE ESCAVADEIRA', 'F168'),
('DENISVAL SANTANA DE B SILVA', 'OP DE ESCAVADEIRA', 'F169'),
('ELIAS RAMOS', 'OP DE ESCAVADEIRA', 'F170'),
('LIVALDO ATANAZIO DA SILVA', 'OP DE ESCAVADEIRA', 'F171'),
('LUCIO YURI PEREIRA DA SILVA', 'OP DE ESCAVADEIRA', 'F172'),

-- OP DE FRESADORA (alfabético)
('BRUNO ALVES DE LIMA', 'OP DE FRESADORA', 'F173'),
('FABIO FERNANDES LIMA', 'OP DE FRESADORA', 'F174'),
('GERALDO VICENTE FERREIRA', 'OP DE FRESADORA', 'F175'),
('TIAGO SALUSTRIANO DE FARIAS', 'OP DE FRESADORA', 'F176'),
('WILLIAN COSTA OLIVEIRA', 'OP DE FRESADORA', 'F177'),

-- OP DE KMA (alfabético)
('AUGUSTO FERREIRA CAMPOS NETO', 'OP DE KMA', 'F178'),
('CRISTHIAN BRANDAO SILVA', 'OP DE KMA', 'F179'),
('EWERTON JONAS AQUINO LIMA', 'OP DE KMA', 'F180'),
('FERNANDO MIRANDA SOUZA SILVA', 'OP DE KMA', 'F181'),
('IAGO DA SILVA RIBEIRO', 'OP DE KMA', 'F182'),
('JAILSON MARTINS FELICIANO', 'OP DE KMA', 'F183'),
('MAYCON VINICIUS NUNES PEREIRA', 'OP DE KMA', 'F184'),
('WELINTON DE OLIVEIRA GONCALVES', 'OP DE KMA', 'F185'),

-- OP DE PA CARREGADEIRA
('ADAILTO ARCANJO MATOS', 'OP DE PA CARREGADEIRA', 'F186'),

-- OP DE RETROESCAVADEIRA (alfabético)
('ANDERSON HENRIQUE DE SOUSA', 'OP DE RETROESCAVADEIRA', 'F187'),
('CAIO CESAR BEZERRA TORRES', 'OP DE RETROESCAVADEIRA', 'F188'),
('CAIO CESAR MAIA DOS SANTOS', 'OP DE RETROESCAVADEIRA', 'F189'),
('EDILSON ALEXANDRE DA SILVA', 'OP DE RETROESCAVADEIRA', 'F190'),
('LEANDRO DO NASCIMENTO SILVA', 'OP DE RETROESCAVADEIRA', 'F191'),
('RAFAEL DO NASCIMENTO', 'OP DE RETROESCAVADEIRA', 'F192'),
('SAMUEL ARANHA DOS SANTOS', 'OP DE RETROESCAVADEIRA', 'F193'),
('SEBASTIAO XAVIER SOUSA', 'OP DE RETROESCAVADEIRA', 'F194'),

-- OP DE ROLO (alfabético)
('ALEX ALVES COSTA', 'OP DE ROLO', 'F195'),
('ALESSANDRO PONTES', 'OP DE ROLO', 'F196'),
('CLODOALDO DE OLIVEIRA', 'OP DE ROLO', 'F197'),
('ELI FRANCISCO DE SOUSA', 'OP DE ROLO', 'F198'),
('EUDES NUNES ALVES FILHO', 'OP DE ROLO', 'F199'),
('GERALDO ALVES PEREIRA', 'OP DE ROLO', 'F200'),
('ISLANDIO DA SILVA SANTOS', 'OP DE ROLO', 'F201'),
('JOAO VICTOR RODRIGUES PEREIRA', 'OP DE ROLO', 'F202'),
('JOSE ROSIMEIRE SILVA BASTO', 'OP DE ROLO', 'F203'),
('JOSENILDO MOREIRA CRUZ', 'OP DE ROLO', 'F204'),
('LUCIANO DA SILVA SANTOS', 'OP DE ROLO', 'F205'),
('MARCONE JOSE DOS SANTOS', 'OP DE ROLO', 'F206'),
('REGINALDO PEREIRA DE ANDRADE', 'OP DE ROLO', 'F207'),
('RICARDO ALVES DE OLIVEIRA', 'OP DE ROLO', 'F208'),
('UENDSON SILVA SIQUEIRA', 'OP DE ROLO', 'F209'),
('WALLAS FERNANDO DE OLIVEIRA', 'OP DE ROLO', 'F210'),

-- OP DE VIBROACABADORA (alfabético)
('DIOGO HENDERSON DE J BANDEIRA', 'OP DE VIBROACABADORA', 'F211'),
('DIOGO SANTANA BATISTA', 'OP DE VIBROACABADORA', 'F212'),
('FRANCISCO PATRICIO F VIEIRA', 'OP DE VIBROACABADORA', 'F213'),
('RICARDO BARBIERI', 'OP DE VIBROACABADORA', 'F214'),

-- OP SOLO (alfabético)
('GERFFESSON RODRIGUES SANTOS', 'OP SOLO', 'F215'),
('GUILHERME MORALES DE JESUS', 'OP SOLO', 'F216'),
('MATHEUS SATURNINO DOS SANTOS', 'OP SOLO', 'F217'),
('VITOR JUNIO SOUSA DE OLIVEIRA', 'OP SOLO', 'F218'),

-- OPERADOR TRATOR ESTEIRA
('RAFAEL DE LIMA BEZERRA', 'OPERADOR TRATOR ESTEIRA', 'F219'),

-- PEDREIRO (alfabético)
('NICHOLAS ROSA M DE SOUZA', 'PEDREIRO', 'F220'),
('RAFAEL DE SOUZA OLIVEIRA', 'PEDREIRO', 'F221'),
('RAIMUNDO NONATO SANTOS SILVA', 'PEDREIRO', 'F222'),
('ROQUE SANTOS', 'PEDREIRO', 'F223'),
('VALTER ALVES COSTA', 'PEDREIRO', 'F224'),

-- RASTELEIRO (alfabético)
('ADENILDO GOMES DA SILVA', 'RASTELEIRO', 'F225'),
('ALCIMAR GONCALVES DA COSTA', 'RASTELEIRO', 'F226'),
('ANDERSON MIRANDA DOS SANTOS', 'RASTELEIRO', 'F227'),
('ANTONIO ALUIZIO F DE SOUZA', 'RASTELEIRO', 'F228'),
('BATISTA NETO DA S BASTOS', 'RASTELEIRO', 'F229'),
('EDUARDO LOPES MOREIRA', 'RASTELEIRO', 'F230'),
('FRANCISCO CAETANO BALBINO', 'RASTELEIRO', 'F231'),
('FRANCISCO DE ASSIS PEREIRA', 'RASTELEIRO', 'F232'),
('JUAREZ SILVA SANTOS', 'RASTELEIRO', 'F233'),
('LINDOMAR TORRES SOUSA', 'RASTELEIRO', 'F234'),
('MAURO QUEIROZ GOMES', 'RASTELEIRO', 'F235'),
('PERIVALDO BARBOZA B DE SOUZA', 'RASTELEIRO', 'F236'),
('RAI DO NASCIMENTO RODRIGUES', 'RASTELEIRO', 'F237'),
('VITOR PABLO DE SOUSA LIMA', 'RASTELEIRO', 'F238'),
('WELIO SATIRO DO VALE', 'RASTELEIRO', 'F239'),

-- SINALEIRO (alfabético)
('ARILSON JOSE DE SOUZA GOMES', 'SINALEIRO', 'F240'),
('CICERO VANIQUE FILHO', 'SINALEIRO', 'F241'),
('ELIELSON LUSINARIO DA SILVA', 'SINALEIRO', 'F242'),
('LUCAS ROCHA DE SOUSA', 'SINALEIRO', 'F243'),
('NEANDRO DE SOUZA CAVALCANTE', 'SINALEIRO', 'F244'),

-- TEC DE SEGURANÇA (alfabético)
('ALAN DIAS DA SILVA', 'TEC DE SEGURANÇA', 'F245'),
('ALEXANDRE DOS SANTOS COSTA', 'TEC DE SEGURANÇA', 'F246'),
('EDIMAR NOVAIS SILVA', 'TEC DE SEGURANÇA', 'F247'),
('FLADIMIR WESLEY ARAUJO', 'TEC DE SEGURANÇA', 'F248'),
('PLINIO DIASSIS DO NASCIMENTO', 'TEC DE SEGURANÇA', 'F249'),
('SILVIA DE OLIVEIRA', 'TEC DE SEGURANÇA', 'F250');
